/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controle.FacadeCliente;
import controle.FacadeFornecedor;
import controle.FacadeProduto;
import controle.FacadeVenda;
import javax.swing.JOptionPane;
import modelo.Cliente;
import modelo.Fornecedor;
import modelo.Produto;
import modelo.Venda;
import view.helper.Helper;

/**
 *
 * @author Andre
 */
public class HomeView extends javax.swing.JFrame
{
    //Controller co cliente
    FacadeCliente controllerCli = new FacadeCliente();
    FacadeProduto controllerProd = new FacadeProduto();
    FacadeFornecedor controllerFor = new FacadeFornecedor();
    FacadeVenda controllerVend = new FacadeVenda();
    Helper helper = null;
    

    /**
     * Creates new form ClienteView
     */
    public HomeView()
    {
	initComponents();	
	helper = new Helper(this);
	helper.setLayout(1);
    }
             
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        pnlCabecalho = new javax.swing.JPanel();
        lblTituloTela = new javax.swing.JLabel();
        jPaneMain = new javax.swing.JPanel();
        jPanelCard = new javax.swing.JPanel();
        jPanelCliente = new javax.swing.JPanel();
        jPanels1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfNome = new javax.swing.JTextField();
        jPanels2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jtfSobrenome = new javax.swing.JTextField();
        jPanels3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jftfDataNasc = new javax.swing.JFormattedTextField();
        jPanels4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jftfCPF = new javax.swing.JFormattedTextField();
        jPanels5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jftfRG = new javax.swing.JFormattedTextField();
        jbCadastrarCli = new javax.swing.JButton();
        jbCancelarCli = new javax.swing.JButton();
        jPanels7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jtfPesquisa = new javax.swing.JTextField();
        jbPesquisar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlistCliente = new javax.swing.JList<>();
        jPanelBotoesCli = new javax.swing.JPanel();
        jbRemoverCli = new javax.swing.JButton();
        jbAlterarCli = new javax.swing.JButton();
        jPanelProduto = new javax.swing.JPanel();
        jPanels8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jtfNomeProd = new javax.swing.JTextField();
        jPanels9 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jtfDescricao = new javax.swing.JTextField();
        jPanels10 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jftfDataValidade = new javax.swing.JFormattedTextField();
        jPanels12 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jftfMarca = new javax.swing.JTextField();
        jbCadastrarProd = new javax.swing.JButton();
        jbCancelarProd = new javax.swing.JButton();
        jPanels13 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jtfPesquisaProd = new javax.swing.JTextField();
        jbPesquisarProd = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlistProduto = new javax.swing.JList<>();
        jPanelsBotoesProd = new javax.swing.JPanel();
        jbRemoverProd = new javax.swing.JButton();
        jbAlterarProd = new javax.swing.JButton();
        jPanelFornecedor = new javax.swing.JPanel();
        jPanels6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtfRazao = new javax.swing.JTextField();
        jPanels14 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jtfFantasia = new javax.swing.JTextField();
        jPanels16 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jftfCNPJ = new javax.swing.JFormattedTextField();
        jbCadastrarForn = new javax.swing.JButton();
        jbCancelarForn = new javax.swing.JButton();
        jPanels18 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jtfPesquisaForn = new javax.swing.JTextField();
        jbPesquisarForn = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jlistFornecedor = new javax.swing.JList<>();
        jPanelBotoesForn = new javax.swing.JPanel();
        jbRemoverForn = new javax.swing.JButton();
        jbAlterarForn = new javax.swing.JButton();
        jPanelVenda = new javax.swing.JPanel();
        jPanels11 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jComboCliente = new javax.swing.JComboBox<>();
        jPanels15 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jComboProduto = new javax.swing.JComboBox<>();
        jPanels17 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jftfDataValidade1 = new javax.swing.JFormattedTextField();
        jbCadastrarVenda = new javax.swing.JButton();
        jbCancelarVenda = new javax.swing.JButton();
        jPanels20 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jtfPesquisaVenda = new javax.swing.JTextField();
        jbPesquisarVenda = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jlistVenda = new javax.swing.JList<>();
        jPanelsBotoesProd1 = new javax.swing.JPanel();
        jbRemoverVenda = new javax.swing.JButton();
        jbAlterarVenda = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCliente = new javax.swing.JMenu();
        jMenuProduto = new javax.swing.JMenu();
        jMenuFornecedor = new javax.swing.JMenu();
        jMenuVenda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setName("Home"); // NOI18N

        pnlCabecalho.setBackground(new java.awt.Color(110, 99, 197));

        lblTituloTela.setBackground(new java.awt.Color(255, 255, 255));
        lblTituloTela.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        lblTituloTela.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloTela.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTituloTela.setText("Cadastro...");
        lblTituloTela.setPreferredSize(new java.awt.Dimension(228, 30));

        javax.swing.GroupLayout pnlCabecalhoLayout = new javax.swing.GroupLayout(pnlCabecalho);
        pnlCabecalho.setLayout(pnlCabecalhoLayout);
        pnlCabecalhoLayout.setHorizontalGroup(
            pnlCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCabecalhoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloTela, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlCabecalhoLayout.setVerticalGroup(
            pnlCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCabecalhoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloTela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPaneMain.setBackground(new java.awt.Color(255, 255, 255));
        jPaneMain.setPreferredSize(new java.awt.Dimension(776, 729));

        jPanelCard.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCard.setLayout(new java.awt.CardLayout());

        jPanelCliente.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCliente.setForeground(new java.awt.Color(204, 255, 204));

        jPanels1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Nome");

        jtfNome.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout jPanels1Layout = new javax.swing.GroupLayout(jPanels1);
        jPanels1.setLayout(jPanels1Layout);
        jPanels1Layout.setHorizontalGroup(
            jPanels1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtfNome)
            .addGroup(jPanels1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanels1Layout.setVerticalGroup(
            jPanels1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanels1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfNome, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
        );

        jPanels2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Sobrenome");

        jtfSobrenome.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout jPanels2Layout = new javax.swing.GroupLayout(jPanels2);
        jPanels2.setLayout(jPanels2Layout);
        jPanels2Layout.setHorizontalGroup(
            jPanels2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtfSobrenome)
            .addGroup(jPanels2Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 218, Short.MAX_VALUE))
        );
        jPanels2Layout.setVerticalGroup(
            jPanels2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanels2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfSobrenome, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
        );

        jPanels3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Data Nascimento");

        jftfDataNasc.setBackground(new java.awt.Color(255, 255, 204));
        try
        {
            jftfDataNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex)
        {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanels3Layout = new javax.swing.GroupLayout(jPanels3);
        jPanels3.setLayout(jPanels3Layout);
        jPanels3Layout.setHorizontalGroup(
            jPanels3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanels3Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanels3Layout.createSequentialGroup()
                .addComponent(jftfDataNasc)
                .addContainerGap())
        );
        jPanels3Layout.setVerticalGroup(
            jPanels3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanels3Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jftfDataNasc, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
        );

        jPanels4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("CPF");

        jftfCPF.setBackground(new java.awt.Color(255, 255, 204));
        try
        {
            jftfCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex)
        {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanels4Layout = new javax.swing.GroupLayout(jPanels4);
        jPanels4.setLayout(jPanels4Layout);
        jPanels4Layout.setHorizontalGroup(
            jPanels4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanels4Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanels4Layout.createSequentialGroup()
                .addComponent(jftfCPF)
                .addContainerGap())
        );
        jPanels4Layout.setVerticalGroup(
            jPanels4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanels4Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jftfCPF, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
        );

        jPanels5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("RG");

        jftfRG.setBackground(new java.awt.Color(255, 255, 204));
        try
        {
            jftfRG.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-###-###-#")));
        } catch (java.text.ParseException ex)
        {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanels5Layout = new javax.swing.GroupLayout(jPanels5);
        jPanels5.setLayout(jPanels5Layout);
        jPanels5Layout.setHorizontalGroup(
            jPanels5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanels5Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanels5Layout.createSequentialGroup()
                .addComponent(jftfRG)
                .addContainerGap())
        );
        jPanels5Layout.setVerticalGroup(
            jPanels5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanels5Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jftfRG, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
        );

        jbCadastrarCli.setText("Cadastrar");
        jbCadastrarCli.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jbCadastrarCliActionPerformed(evt);
            }
        });

        jbCancelarCli.setText("Cancelar");
        jbCancelarCli.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jbCancelarCliActionPerformed(evt);
            }
        });

        jPanels7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Pesquisa");

        jtfPesquisa.setBackground(new java.awt.Color(255, 255, 204));

        jbPesquisar.setText("Pesquisar");
        jbPesquisar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jbPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanels7Layout = new javax.swing.GroupLayout(jPanels7);
        jPanels7.setLayout(jPanels7Layout);
        jPanels7Layout.setHorizontalGroup(
            jPanels7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanels7Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanels7Layout.createSequentialGroup()
                .addComponent(jtfPesquisa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanels7Layout.setVerticalGroup(
            jPanels7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanels7Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
            .addGroup(jPanels7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Lista de Clientes :");

        jlistCliente.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(jlistCliente);

        jPanelBotoesCli.setBackground(new java.awt.Color(255, 255, 255));

        jbRemoverCli.setText("Remover");
        jbRemoverCli.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jbRemoverCliActionPerformed(evt);
            }
        });

        jbAlterarCli.setText("Alterar");

        javax.swing.GroupLayout jPanelBotoesCliLayout = new javax.swing.GroupLayout(jPanelBotoesCli);
        jPanelBotoesCli.setLayout(jPanelBotoesCliLayout);
        jPanelBotoesCliLayout.setHorizontalGroup(
            jPanelBotoesCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBotoesCliLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbAlterarCli, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbRemoverCli, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );
        jPanelBotoesCliLayout.setVerticalGroup(
            jPanelBotoesCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbAlterarCli, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
            .addComponent(jbRemoverCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelClienteLayout = new javax.swing.GroupLayout(jPanelCliente);
        jPanelCliente.setLayout(jPanelClienteLayout);
        jPanelClienteLayout.setHorizontalGroup(
            jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanels1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanels2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelClienteLayout.createSequentialGroup()
                        .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelClienteLayout.createSequentialGroup()
                                .addComponent(jbCadastrarCli)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbCancelarCli, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanels5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanels4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanels3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 150, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelBotoesCli, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanels7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelClienteLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 82, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelClienteLayout.setVerticalGroup(
            jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanels1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanels7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelClienteLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(jPanelClienteLayout.createSequentialGroup()
                        .addComponent(jPanels2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jPanels3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanels4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanels5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbCadastrarCli, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                            .addComponent(jbCancelarCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBotoesCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelCard.add(jPanelCliente, "card2");

        jPanelProduto.setBackground(new java.awt.Color(255, 255, 255));
        jPanelProduto.setForeground(new java.awt.Color(255, 0, 0));

        jPanels8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Nome");

        jtfNomeProd.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout jPanels8Layout = new javax.swing.GroupLayout(jPanels8);
        jPanels8.setLayout(jPanels8Layout);
        jPanels8Layout.setHorizontalGroup(
            jPanels8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtfNomeProd)
            .addGroup(jPanels8Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanels8Layout.setVerticalGroup(
            jPanels8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanels8Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfNomeProd, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
        );

        jPanels9.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Descrição:");

        jtfDescricao.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout jPanels9Layout = new javax.swing.GroupLayout(jPanels9);
        jPanels9.setLayout(jPanels9Layout);
        jPanels9Layout.setHorizontalGroup(
            jPanels9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtfDescricao)
            .addGroup(jPanels9Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 218, Short.MAX_VALUE))
        );
        jPanels9Layout.setVerticalGroup(
            jPanels9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanels9Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
        );

        jPanels10.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Data Validade");

        jftfDataValidade.setBackground(new java.awt.Color(255, 255, 204));
        try
        {
            jftfDataValidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex)
        {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanels10Layout = new javax.swing.GroupLayout(jPanels10);
        jPanels10.setLayout(jPanels10Layout);
        jPanels10Layout.setHorizontalGroup(
            jPanels10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanels10Layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanels10Layout.createSequentialGroup()
                .addComponent(jftfDataValidade)
                .addContainerGap())
        );
        jPanels10Layout.setVerticalGroup(
            jPanels10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanels10Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jftfDataValidade, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
        );

        jPanels12.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Marca");

        jftfMarca.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout jPanels12Layout = new javax.swing.GroupLayout(jPanels12);
        jPanels12.setLayout(jPanels12Layout);
        jPanels12Layout.setHorizontalGroup(
            jPanels12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanels12Layout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanels12Layout.createSequentialGroup()
                .addComponent(jftfMarca)
                .addContainerGap())
        );
        jPanels12Layout.setVerticalGroup(
            jPanels12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanels12Layout.createSequentialGroup()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jftfMarca, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
        );

        jbCadastrarProd.setText("Cadastrar");
        jbCadastrarProd.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jbCadastrarProdActionPerformed(evt);
            }
        });

        jbCancelarProd.setText("Cancelar");
        jbCancelarProd.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jbCancelarProdActionPerformed(evt);
            }
        });

        jPanels13.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Pesquisa");

        jtfPesquisaProd.setBackground(new java.awt.Color(255, 255, 204));

        jbPesquisarProd.setText("Pesquisar");
        jbPesquisarProd.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jbPesquisarProdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanels13Layout = new javax.swing.GroupLayout(jPanels13);
        jPanels13.setLayout(jPanels13Layout);
        jPanels13Layout.setHorizontalGroup(
            jPanels13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanels13Layout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanels13Layout.createSequentialGroup()
                .addComponent(jtfPesquisaProd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbPesquisarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanels13Layout.setVerticalGroup(
            jPanels13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanels13Layout.createSequentialGroup()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfPesquisaProd, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
            .addGroup(jPanels13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbPesquisarProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Lista de Produtos:");

        jlistProduto.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane2.setViewportView(jlistProduto);

        jPanelsBotoesProd.setBackground(new java.awt.Color(255, 255, 255));

        jbRemoverProd.setText("Remover");
        jbRemoverProd.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jbRemoverProdActionPerformed(evt);
            }
        });

        jbAlterarProd.setText("Alterar");
        jbAlterarProd.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jbAlterarProdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelsBotoesProdLayout = new javax.swing.GroupLayout(jPanelsBotoesProd);
        jPanelsBotoesProd.setLayout(jPanelsBotoesProdLayout);
        jPanelsBotoesProdLayout.setHorizontalGroup(
            jPanelsBotoesProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelsBotoesProdLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbAlterarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbRemoverProd, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );
        jPanelsBotoesProdLayout.setVerticalGroup(
            jPanelsBotoesProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbAlterarProd, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
            .addComponent(jbRemoverProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelProdutoLayout = new javax.swing.GroupLayout(jPanelProduto);
        jPanelProduto.setLayout(jPanelProdutoLayout);
        jPanelProdutoLayout.setHorizontalGroup(
            jPanelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanels8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanels9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelProdutoLayout.createSequentialGroup()
                        .addGroup(jPanelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelProdutoLayout.createSequentialGroup()
                                .addComponent(jbCadastrarProd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbCancelarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanels12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanels10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelsBotoesProd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jPanels13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelProdutoLayout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 82, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelProdutoLayout.setVerticalGroup(
            jPanelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanels8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanels13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelProdutoLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2))
                    .addGroup(jPanelProdutoLayout.createSequentialGroup()
                        .addComponent(jPanels9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jPanels10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanels12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120)
                        .addGroup(jPanelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbCadastrarProd, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                            .addComponent(jbCancelarProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelsBotoesProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelCard.add(jPanelProduto, "card2");

        jPanelFornecedor.setBackground(new java.awt.Color(255, 255, 255));
        jPanelFornecedor.setForeground(new java.awt.Color(204, 255, 204));

        jPanels6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Razão");

        jtfRazao.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout jPanels6Layout = new javax.swing.GroupLayout(jPanels6);
        jPanels6.setLayout(jPanels6Layout);
        jPanels6Layout.setHorizontalGroup(
            jPanels6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtfRazao)
            .addGroup(jPanels6Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanels6Layout.setVerticalGroup(
            jPanels6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanels6Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfRazao, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
        );

        jPanels14.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Fantasia");

        jtfFantasia.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout jPanels14Layout = new javax.swing.GroupLayout(jPanels14);
        jPanels14.setLayout(jPanels14Layout);
        jPanels14Layout.setHorizontalGroup(
            jPanels14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtfFantasia)
            .addGroup(jPanels14Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 218, Short.MAX_VALUE))
        );
        jPanels14Layout.setVerticalGroup(
            jPanels14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanels14Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfFantasia, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
        );

        jPanels16.setBackground(new java.awt.Color(255, 255, 255));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("CNPJ");

        jftfCNPJ.setBackground(new java.awt.Color(255, 255, 204));
        try
        {
            jftfCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex)
        {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanels16Layout = new javax.swing.GroupLayout(jPanels16);
        jPanels16.setLayout(jPanels16Layout);
        jPanels16Layout.setHorizontalGroup(
            jPanels16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanels16Layout.createSequentialGroup()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanels16Layout.createSequentialGroup()
                .addComponent(jftfCNPJ)
                .addContainerGap())
        );
        jPanels16Layout.setVerticalGroup(
            jPanels16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanels16Layout.createSequentialGroup()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jftfCNPJ, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
        );

        jbCadastrarForn.setText("Cadastrar");
        jbCadastrarForn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jbCadastrarFornActionPerformed(evt);
            }
        });

        jbCancelarForn.setText("Cancelar");
        jbCancelarForn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jbCancelarFornActionPerformed(evt);
            }
        });

        jPanels18.setBackground(new java.awt.Color(255, 255, 255));

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setText("Pesquisa");

        jtfPesquisaForn.setBackground(new java.awt.Color(255, 255, 204));

        jbPesquisarForn.setText("Pesquisar");
        jbPesquisarForn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jbPesquisarFornActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanels18Layout = new javax.swing.GroupLayout(jPanels18);
        jPanels18.setLayout(jPanels18Layout);
        jPanels18Layout.setHorizontalGroup(
            jPanels18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanels18Layout.createSequentialGroup()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanels18Layout.createSequentialGroup()
                .addComponent(jtfPesquisaForn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbPesquisarForn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanels18Layout.setVerticalGroup(
            jPanels18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanels18Layout.createSequentialGroup()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfPesquisaForn, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
            .addGroup(jPanels18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbPesquisarForn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setText("Lista de Fornecedore:");

        jlistFornecedor.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane3.setViewportView(jlistFornecedor);

        jPanelBotoesForn.setBackground(new java.awt.Color(255, 255, 255));

        jbRemoverForn.setText("Remover");
        jbRemoverForn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jbRemoverFornActionPerformed(evt);
            }
        });

        jbAlterarForn.setText("Alterar");
        jbAlterarForn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jbAlterarFornActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBotoesFornLayout = new javax.swing.GroupLayout(jPanelBotoesForn);
        jPanelBotoesForn.setLayout(jPanelBotoesFornLayout);
        jPanelBotoesFornLayout.setHorizontalGroup(
            jPanelBotoesFornLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBotoesFornLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbAlterarForn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbRemoverForn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );
        jPanelBotoesFornLayout.setVerticalGroup(
            jPanelBotoesFornLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbAlterarForn, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
            .addComponent(jbRemoverForn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelFornecedorLayout = new javax.swing.GroupLayout(jPanelFornecedor);
        jPanelFornecedor.setLayout(jPanelFornecedorLayout);
        jPanelFornecedorLayout.setHorizontalGroup(
            jPanelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFornecedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanels6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanels14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelFornecedorLayout.createSequentialGroup()
                        .addGroup(jPanelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelFornecedorLayout.createSequentialGroup()
                                .addComponent(jbCadastrarForn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbCancelarForn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanels16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 150, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelBotoesForn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3)
                    .addComponent(jPanels18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelFornecedorLayout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 82, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelFornecedorLayout.setVerticalGroup(
            jPanelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFornecedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanels6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanels18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFornecedorLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3))
                    .addGroup(jPanelFornecedorLayout.createSequentialGroup()
                        .addComponent(jPanels14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanels16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(148, 148, 148)
                        .addGroup(jPanelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbCadastrarForn, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                            .addComponent(jbCancelarForn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBotoesForn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelCard.add(jPanelFornecedor, "card2");

        jPanelVenda.setBackground(new java.awt.Color(255, 255, 255));
        jPanelVenda.setForeground(new java.awt.Color(255, 0, 0));

        jPanels11.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Cliente");

        jComboCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione..." }));

        javax.swing.GroupLayout jPanels11Layout = new javax.swing.GroupLayout(jPanels11);
        jPanels11.setLayout(jPanels11Layout);
        jPanels11Layout.setHorizontalGroup(
            jPanels11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanels11Layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 184, Short.MAX_VALUE))
            .addComponent(jComboCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanels11Layout.setVerticalGroup(
            jPanels11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanels11Layout.createSequentialGroup()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
        );

        jPanels15.setBackground(new java.awt.Color(255, 255, 255));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("Produto");

        jComboProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione..." }));

        javax.swing.GroupLayout jPanels15Layout = new javax.swing.GroupLayout(jPanels15);
        jPanels15.setLayout(jPanels15Layout);
        jPanels15Layout.setHorizontalGroup(
            jPanels15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanels15Layout.createSequentialGroup()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jComboProduto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanels15Layout.setVerticalGroup(
            jPanels15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanels15Layout.createSequentialGroup()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
        );

        jPanels17.setBackground(new java.awt.Color(255, 255, 255));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setText("Data da Venda");

        jftfDataValidade1.setBackground(new java.awt.Color(255, 255, 204));
        try
        {
            jftfDataValidade1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex)
        {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanels17Layout = new javax.swing.GroupLayout(jPanels17);
        jPanels17.setLayout(jPanels17Layout);
        jPanels17Layout.setHorizontalGroup(
            jPanels17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanels17Layout.createSequentialGroup()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanels17Layout.createSequentialGroup()
                .addComponent(jftfDataValidade1)
                .addContainerGap())
        );
        jPanels17Layout.setVerticalGroup(
            jPanels17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanels17Layout.createSequentialGroup()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jftfDataValidade1, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
        );

        jbCadastrarVenda.setText("Cadastrar");
        jbCadastrarVenda.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jbCadastrarVendaActionPerformed(evt);
            }
        });

        jbCancelarVenda.setText("Cancelar");
        jbCancelarVenda.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jbCancelarVendaActionPerformed(evt);
            }
        });

        jPanels20.setBackground(new java.awt.Color(255, 255, 255));

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel23.setText("Pesquisa");

        jtfPesquisaVenda.setBackground(new java.awt.Color(255, 255, 204));

        jbPesquisarVenda.setText("Pesquisar");
        jbPesquisarVenda.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jbPesquisarVendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanels20Layout = new javax.swing.GroupLayout(jPanels20);
        jPanels20.setLayout(jPanels20Layout);
        jPanels20Layout.setHorizontalGroup(
            jPanels20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanels20Layout.createSequentialGroup()
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanels20Layout.createSequentialGroup()
                .addComponent(jtfPesquisaVenda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbPesquisarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanels20Layout.setVerticalGroup(
            jPanels20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanels20Layout.createSequentialGroup()
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfPesquisaVenda, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
            .addGroup(jPanels20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbPesquisarVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel24.setText("Lista de Vendas:");

        jlistVenda.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane4.setViewportView(jlistVenda);

        jPanelsBotoesProd1.setBackground(new java.awt.Color(255, 255, 255));

        jbRemoverVenda.setText("Remover");
        jbRemoverVenda.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jbRemoverVendaActionPerformed(evt);
            }
        });

        jbAlterarVenda.setText("Alterar");
        jbAlterarVenda.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jbAlterarVendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelsBotoesProd1Layout = new javax.swing.GroupLayout(jPanelsBotoesProd1);
        jPanelsBotoesProd1.setLayout(jPanelsBotoesProd1Layout);
        jPanelsBotoesProd1Layout.setHorizontalGroup(
            jPanelsBotoesProd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelsBotoesProd1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbAlterarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbRemoverVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );
        jPanelsBotoesProd1Layout.setVerticalGroup(
            jPanelsBotoesProd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbAlterarVenda, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
            .addComponent(jbRemoverVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelVendaLayout = new javax.swing.GroupLayout(jPanelVenda);
        jPanelVenda.setLayout(jPanelVendaLayout);
        jPanelVendaLayout.setHorizontalGroup(
            jPanelVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVendaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanels11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanels15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanelVendaLayout.createSequentialGroup()
                            .addComponent(jbCadastrarVenda)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbCancelarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanels17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelsBotoesProd1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4)
                    .addComponent(jPanels20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelVendaLayout.createSequentialGroup()
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 116, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelVendaLayout.setVerticalGroup(
            jPanelVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVendaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanels11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanels20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelVendaLayout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelsBotoesProd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelVendaLayout.createSequentialGroup()
                        .addComponent(jPanels15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jPanels17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(184, 184, 184)
                        .addGroup(jPanelVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbCadastrarVenda, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                            .addComponent(jbCancelarVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );

        jPanelCard.add(jPanelVenda, "card2");

        javax.swing.GroupLayout jPaneMainLayout = new javax.swing.GroupLayout(jPaneMain);
        jPaneMain.setLayout(jPaneMainLayout);
        jPaneMainLayout.setHorizontalGroup(
            jPaneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPaneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPaneMainLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPaneMainLayout.setVerticalGroup(
            jPaneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 582, Short.MAX_VALUE)
            .addGroup(jPaneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneMainLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelCard, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jMenuBar1.setBorder(null);

        jMenuCliente.setText("Cliente");
        jMenuCliente.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jMenuClienteMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuCliente);

        jMenuProduto.setText("Produto");
        jMenuProduto.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jMenuProdutoMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuProduto);

        jMenuFornecedor.setText("Fornecedor");
        jMenuFornecedor.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jMenuFornecedorMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuFornecedor);

        jMenuVenda.setText("Venda");
        jMenuVenda.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jMenuVendaMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuVenda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlCabecalho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPaneMain, javax.swing.GroupLayout.DEFAULT_SIZE, 772, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnlCabecalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPaneMain, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(788, 702));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuClienteMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jMenuClienteMouseClicked
    {//GEN-HEADEREND:event_jMenuClienteMouseClicked
	helper.setLayout(1);	
    }//GEN-LAST:event_jMenuClienteMouseClicked

    private void jMenuProdutoMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jMenuProdutoMouseClicked
    {//GEN-HEADEREND:event_jMenuProdutoMouseClicked
	helper.setLayout(2);
    }//GEN-LAST:event_jMenuProdutoMouseClicked

    private void jMenuVendaMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jMenuVendaMouseClicked
    {//GEN-HEADEREND:event_jMenuVendaMouseClicked
	helper.setLayout(4);
    }//GEN-LAST:event_jMenuVendaMouseClicked

    private void jMenuFornecedorMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jMenuFornecedorMouseClicked
    {//GEN-HEADEREND:event_jMenuFornecedorMouseClicked
	helper.setLayout(3);
    }//GEN-LAST:event_jMenuFornecedorMouseClicked

    private void jbCadastrarCliActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jbCadastrarCliActionPerformed
    {//GEN-HEADEREND:event_jbCadastrarCliActionPerformed
        Cliente cliente = new Cliente();
	cliente = helper.loadCliente();
        cliente.setId(controllerCli.getTodosClientes().size() + 1);
	
	//Add obj na lista:        
        controllerCli.inserirCliente(cliente);
        
	//atualizar a lista na tela:
        jlistCliente.setListData(controllerCli.getTodosClientes().toArray());
	
	//Atualiza combo cliente:
	helper.loadComboClientes(controllerCli.getTodosClientes());
	
	//Mensagem
	JOptionPane.showMessageDialog(null, "Cliente "+ cliente.getNome()+ " cadastrado com sucesso!", "Sucesso", 1);
    }//GEN-LAST:event_jbCadastrarCliActionPerformed

    private void jbRemoverCliActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jbRemoverCliActionPerformed
    {//GEN-HEADEREND:event_jbRemoverCliActionPerformed
        Cliente cliente = (Cliente) jlistCliente.getSelectedValue();        
	
        controllerCli.removerCliente(cliente.getId()); 
        
	//atualizar a lista em tela:
        jlistCliente.setListData(controllerCli.getTodosClientes().toArray());
	
	//Mensagem
	JOptionPane.showMessageDialog(null, "Cliente "+ cliente.getId() + " removido com sucesso!", "Sucesso", 1);
    }//GEN-LAST:event_jbRemoverCliActionPerformed

    private void jbPesquisarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jbPesquisarActionPerformed
    {//GEN-HEADEREND:event_jbPesquisarActionPerformed
        String txtPesquisa = jtfPesquisa.getText(); 
        
	//atualizar a lista em tela:
        jlistCliente.setListData(controllerCli.pesquisarClientePorNome(txtPesquisa).toArray());   
    }//GEN-LAST:event_jbPesquisarActionPerformed

    private void jbRemoverProdActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jbRemoverProdActionPerformed
    {//GEN-HEADEREND:event_jbRemoverProdActionPerformed
        Produto produto = (Produto) jlistProduto.getSelectedValue();
        
        controllerProd.removerProduto(produto.getId()); 
        
	//atualizar a lista em tela:
        jlistProduto.setListData(controllerProd.getTodosProdutos().toArray());
	
	//Mensagem
	JOptionPane.showMessageDialog(null, "Produto "+ produto.getId() + " removido com sucesso!", "Sucesso", 1);
    }//GEN-LAST:event_jbRemoverProdActionPerformed

    private void jbCadastrarProdActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jbCadastrarProdActionPerformed
    {//GEN-HEADEREND:event_jbCadastrarProdActionPerformed
        Produto produto = new Produto();
	produto = helper.loadProduto();
        produto.setId(controllerProd.getTodosProdutos().size() + 1);

        //add na lista
        controllerProd.inserirProduto(produto);
        
	//atualizar a lista em tela:
        jlistProduto.setListData(controllerProd.getTodosProdutos().toArray());
	
	//atualzia combo produto
	helper.loadComboProdutos(controllerProd.getTodosProdutos()); 
	
	//Mensagem
	JOptionPane.showMessageDialog(null, "Produto "+ produto.getNome()+ " cadastrado com sucesso!", "Sucesso", 1);
    }//GEN-LAST:event_jbCadastrarProdActionPerformed

    private void jbPesquisarProdActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jbPesquisarProdActionPerformed
    {//GEN-HEADEREND:event_jbPesquisarProdActionPerformed
        String txtPesquisa = jtfPesquisaProd.getText(); 
        
	//atualizar a lista em tela:
        jlistProduto.setListData(controllerProd.pesquisarProdutoPorNome(txtPesquisa).toArray());  
    }//GEN-LAST:event_jbPesquisarProdActionPerformed

    private void jbCancelarProdActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jbCancelarProdActionPerformed
    {//GEN-HEADEREND:event_jbCancelarProdActionPerformed
        // TODO add your handling code here:
	JOptionPane.showMessageDialog(null, "Não implementado!", "Aviso", 1);
    }//GEN-LAST:event_jbCancelarProdActionPerformed

    private void jbAlterarProdActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jbAlterarProdActionPerformed
    {//GEN-HEADEREND:event_jbAlterarProdActionPerformed
        // TODO add your handling code here:
	JOptionPane.showMessageDialog(null, "Não implementado!", "Aviso", 1);
    }//GEN-LAST:event_jbAlterarProdActionPerformed

    private void jbCadastrarFornActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jbCadastrarFornActionPerformed
    {//GEN-HEADEREND:event_jbCadastrarFornActionPerformed
        Fornecedor fornecedor = new Fornecedor();
	fornecedor = helper.loadFornecedor();
        fornecedor.setId(controllerFor.getTodosFornecedores().size() + 1);
        
        //add.
        controllerFor.inserirFornecedor(fornecedor);
        
	//atualizar a lista em tela:
        jlistFornecedor.setListData(controllerFor.getTodosFornecedores().toArray());
	
	//Mensagem
	JOptionPane.showMessageDialog(null, "Fornecedor "+ fornecedor.getRazao() + " cadastrado com sucesso!", "Sucesso", 1);
    }//GEN-LAST:event_jbCadastrarFornActionPerformed

    private void jbPesquisarFornActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jbPesquisarFornActionPerformed
    {//GEN-HEADEREND:event_jbPesquisarFornActionPerformed
        String txtPesquisa = jtfPesquisaForn.getText();
        
	//atualizar a lista em tela:
        jlistFornecedor.setListData(controllerFor.pesquisarFornecedorPorRazao(txtPesquisa).toArray()); 
    }//GEN-LAST:event_jbPesquisarFornActionPerformed

    private void jbRemoverFornActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jbRemoverFornActionPerformed
    {//GEN-HEADEREND:event_jbRemoverFornActionPerformed
        Fornecedor fornecedor = (Fornecedor) jlistFornecedor.getSelectedValue();
        
        controllerProd.removerProduto(fornecedor.getId()); 
        
	//atualizar a lista em tela:
        jlistFornecedor.setListData(controllerFor.getTodosFornecedores().toArray());
	
	//Mensagem
	JOptionPane.showMessageDialog(null, "Fornecedor "+ fornecedor.getId() + " removido com sucesso!", "Sucesso", 1);
    }//GEN-LAST:event_jbRemoverFornActionPerformed

    private void jbCancelarFornActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jbCancelarFornActionPerformed
    {//GEN-HEADEREND:event_jbCancelarFornActionPerformed
	// TODO add your handling code here:
	JOptionPane.showMessageDialog(null, "Não implementado!", "Aviso", 1);
    }//GEN-LAST:event_jbCancelarFornActionPerformed

    private void jbAlterarFornActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jbAlterarFornActionPerformed
    {//GEN-HEADEREND:event_jbAlterarFornActionPerformed
        // TODO add your handling code here:
	JOptionPane.showMessageDialog(null, "Não implementado!", "Aviso", 1);
    }//GEN-LAST:event_jbAlterarFornActionPerformed

    private void jbCadastrarVendaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jbCadastrarVendaActionPerformed
    {//GEN-HEADEREND:event_jbCadastrarVendaActionPerformed
        Venda venda = new Venda(); 
        venda.setId(controllerVend.getTodasVendas().size() + 1);
        venda.setCliente((Cliente)jComboCliente.getSelectedItem());
	venda.setProduto((Produto)jComboProduto.getSelectedItem());       
        
        controllerVend.inserirVenda(venda);
        
	//atualizar a lista em tela:
        jlistVenda.setListData(controllerVend.getTodasVendas().toArray());
	
	//Mensagem
	JOptionPane.showMessageDialog(null, "Venda "+ venda.getId()+ " cadastrada com sucesso!", "Sucesso", 1);
    }//GEN-LAST:event_jbCadastrarVendaActionPerformed

    private void jbCancelarVendaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jbCancelarVendaActionPerformed
    {//GEN-HEADEREND:event_jbCancelarVendaActionPerformed
        // TODO add your handling code here:
	JOptionPane.showMessageDialog(null, "Não implementado!", "Aviso", 1);
    }//GEN-LAST:event_jbCancelarVendaActionPerformed

    private void jbPesquisarVendaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jbPesquisarVendaActionPerformed
    {//GEN-HEADEREND:event_jbPesquisarVendaActionPerformed
        String txtPesquisa = jtfPesquisaVenda.getText(); 
        
	//atualizar a lista em tela:
        jlistVenda.setListData(controllerVend.pesquisarVenda(txtPesquisa).toArray());  
    }//GEN-LAST:event_jbPesquisarVendaActionPerformed

    private void jbRemoverVendaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jbRemoverVendaActionPerformed
    {//GEN-HEADEREND:event_jbRemoverVendaActionPerformed
        Venda venda = (Venda) jlistVenda.getSelectedValue();
        
        controllerVend.removerVenda(venda.getId()); 
        
	//atualizar a lista em tela:
        jlistVenda.setListData(controllerVend.getTodasVendas().toArray());
	
	//Mensagem
	JOptionPane.showMessageDialog(null, "Venda "+ venda.getId() + " removida com sucesso!", "Sucesso", 1);
    }//GEN-LAST:event_jbRemoverVendaActionPerformed

    private void jbAlterarVendaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jbAlterarVendaActionPerformed
    {//GEN-HEADEREND:event_jbAlterarVendaActionPerformed
        // TODO add your handling code here:
	JOptionPane.showMessageDialog(null, "Não implementado!", "Aviso", 1);
    }//GEN-LAST:event_jbAlterarVendaActionPerformed

    private void jbCancelarCliActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jbCancelarCliActionPerformed
    {//GEN-HEADEREND:event_jbCancelarCliActionPerformed
        // TODO add your handling code here:
	JOptionPane.showMessageDialog(null, "Não implementado!", "Aviso", 1);
    }//GEN-LAST:event_jbCancelarCliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
	/*
	 * Set the Nimbus look and feel
	 */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/*
	 * If Nimbus (introduced in Java SE 6) is not available, stay with the
	 * default look and feel. For details see
	 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
	 */
	try
	{
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
	    {
		if ("Windows".equals(info.getName()))
		{
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	}
	catch (ClassNotFoundException ex)
	{
	    java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	catch (InstantiationException ex)
	{
	    java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	catch (IllegalAccessException ex)
	{
	    java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	catch (javax.swing.UnsupportedLookAndFeelException ex)
	{
	    java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>
	//</editor-fold>

	/*
	 * Create and display the form
	 */
	java.awt.EventQueue.invokeLater(new Runnable()
	{
	    public void run()
	    {
		new HomeView().setVisible(true);
	    }

	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> jComboCliente;
    public javax.swing.JComboBox<String> jComboProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCliente;
    private javax.swing.JMenu jMenuFornecedor;
    private javax.swing.JMenu jMenuProduto;
    private javax.swing.JMenu jMenuVenda;
    private javax.swing.JPanel jPaneMain;
    private javax.swing.JPanel jPanelBotoesCli;
    private javax.swing.JPanel jPanelBotoesForn;
    private javax.swing.JPanel jPanelCard;
    public javax.swing.JPanel jPanelCliente;
    public javax.swing.JPanel jPanelFornecedor;
    public javax.swing.JPanel jPanelProduto;
    public javax.swing.JPanel jPanelVenda;
    private javax.swing.JPanel jPanels1;
    private javax.swing.JPanel jPanels10;
    private javax.swing.JPanel jPanels11;
    private javax.swing.JPanel jPanels12;
    private javax.swing.JPanel jPanels13;
    private javax.swing.JPanel jPanels14;
    private javax.swing.JPanel jPanels15;
    private javax.swing.JPanel jPanels16;
    private javax.swing.JPanel jPanels17;
    private javax.swing.JPanel jPanels18;
    private javax.swing.JPanel jPanels2;
    private javax.swing.JPanel jPanels20;
    private javax.swing.JPanel jPanels3;
    private javax.swing.JPanel jPanels4;
    private javax.swing.JPanel jPanels5;
    private javax.swing.JPanel jPanels6;
    private javax.swing.JPanel jPanels7;
    private javax.swing.JPanel jPanels8;
    private javax.swing.JPanel jPanels9;
    private javax.swing.JPanel jPanelsBotoesProd;
    private javax.swing.JPanel jPanelsBotoesProd1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton jbAlterarCli;
    private javax.swing.JButton jbAlterarForn;
    private javax.swing.JButton jbAlterarProd;
    private javax.swing.JButton jbAlterarVenda;
    private javax.swing.JButton jbCadastrarCli;
    private javax.swing.JButton jbCadastrarForn;
    private javax.swing.JButton jbCadastrarProd;
    private javax.swing.JButton jbCadastrarVenda;
    private javax.swing.JButton jbCancelarCli;
    private javax.swing.JButton jbCancelarForn;
    private javax.swing.JButton jbCancelarProd;
    private javax.swing.JButton jbCancelarVenda;
    private javax.swing.JButton jbPesquisar;
    private javax.swing.JButton jbPesquisarForn;
    private javax.swing.JButton jbPesquisarProd;
    private javax.swing.JButton jbPesquisarVenda;
    private javax.swing.JButton jbRemoverCli;
    private javax.swing.JButton jbRemoverForn;
    private javax.swing.JButton jbRemoverProd;
    private javax.swing.JButton jbRemoverVenda;
    public javax.swing.JFormattedTextField jftfCNPJ;
    public javax.swing.JFormattedTextField jftfCPF;
    public javax.swing.JFormattedTextField jftfDataNasc;
    public javax.swing.JFormattedTextField jftfDataValidade;
    public javax.swing.JFormattedTextField jftfDataValidade1;
    public javax.swing.JTextField jftfMarca;
    public javax.swing.JFormattedTextField jftfRG;
    private javax.swing.JList<Object> jlistCliente;
    public javax.swing.JList<Object> jlistFornecedor;
    public javax.swing.JList<Object> jlistProduto;
    private javax.swing.JList<Object> jlistVenda;
    public javax.swing.JTextField jtfDescricao;
    public javax.swing.JTextField jtfFantasia;
    public javax.swing.JTextField jtfNome;
    public javax.swing.JTextField jtfNomeProd;
    public javax.swing.JTextField jtfPesquisa;
    public javax.swing.JTextField jtfPesquisaForn;
    public javax.swing.JTextField jtfPesquisaProd;
    private javax.swing.JTextField jtfPesquisaVenda;
    public javax.swing.JTextField jtfRazao;
    public javax.swing.JTextField jtfSobrenome;
    public javax.swing.JLabel lblTituloTela;
    public javax.swing.JPanel pnlCabecalho;
    // End of variables declaration//GEN-END:variables
}
